---
- name: bootstrap Python 2.x for Ubuntu 16.04
  hosts: "tag_Service_myhadoop"
  remote_user: ubuntu
  become: yes
  gather_facts: no

  tasks:
    - debug: msg="Working on init instance"
    - raw: "if ! which python2.7; then apt-get update -qqy && apt-get install -y python; fi"

- name: install and config hadoop
  hosts: "tag_Service_myhadoop"
  remote_user: ubuntu
  become: yes

  vars_files:
    - vars/common.yml

  roles:
    - openjdk-etc
    - hadoop
