---
- name: check if hdfs formated
  stat: path={{hdfs_dir}}/current
  register: hdfs_formated

- name: format hdfs
  shell: "{{hadoop_home}}/bin/hdfs namenode -format {{cluster_name}}"
  when: hdfs_formated.stat.exists == False
  become: no
  args:
    chdir: "{{hadoop_home}}"
    executable: /bin/bash
  
- name: start name node master
  shell: "pidof java || (nohup {{hadoop_home}}/bin/hdfs --daemon start namenode &)"
  become: no
  args:
    chdir: "{{hadoop_home}}"
    executable: /bin/bash
